{
ANSI =>
	{
	# you can defined aliases too
	# alarm => 'bright_red on_bright_yellwo',
	reset => 'reset',
	
	white => 'white',
	black => 'black',
	green => 'green',
	yellow => 'yellow',
	cyan => 'cyan',
	red => 'red',
	blue => 'blue',
	magenta => 'magenta',
	
	bright_white => 'bright_white',
	bright_black => 'bright_black',
	bright_green => 'bright_green',
	bright_yellow => 'bright_yellow',
	bright_cyan => 'bright_cyan',
	bright_red => 'bright_red',
	bright_blue => 'bright_blue',
	bright_magenta => 'bright_magenta',
	
	on_white => 'on_white',
	on_black => 'on_black',
	on_green => 'on_green',
	on_yellow => 'on_yellow',
	on_cyan => 'on_cyan',
	on_red => 'on_red',
	on_blue => 'on_blue',
	on_magenta => 'on_magenta',
	
	on_bright_white => 'on_bright_white',
	on_bright_black => 'on_bright_black',
	on_bright_green => 'on_bright_green',
	on_bright_yellow => 'on_bright_yellow',
	on_bright_cyan => 'on_bright_cyan',
	on_bright_red => 'on_bright_red',
	on_bright_blue => 'on_bright_blue',
	on_bright_magenta => 'on_bright_magenta',
	},
	
HTML =>
	{
	# any attribute you can put in a span
	reset => '',
	
	white => 'color:#888; ',
	black => 'color:#000; ',
	green => 'color:#080; ',
	yellow => 'color:#880; ',
	cyan => 'color:#088; ',
	red => 'color:#800; ',
	blue => 'color:#008; ',
	magenta => 'color:#808; ',
	
	bright_white => 'color:#fff; ',
	bright_black => 'color:#000; ',
	bright_green => 'color:#0f0; ',
	bright_yellow => 'color:#ff0; ',
	bright_cyan => 'color:#0ff; ',
	bright_red => 'color:#f00; ',
	bright_blue => 'color:#00f; ',
	bright_magenta => 'color:#f0f; ',

	on_white => 'background-color:#888; ',
	on_black => 'background-color:#000; ',
	on_green => 'background-color:#080; ',
	on_yellow => 'background-color:#880; ',
	on_cyan => 'background-color:#088; ',
	on_red => 'background-color:#800; ',
	on_blue => 'background-color:#008; ',
	on_magenta => 'background-color:#808; ',
	
	on_bright_white => 'background-color:#fff; ',
	on_bright_black => 'background-color:#000; ',
	on_bright_green => 'background-color:#0f0; ',
	on_bright_yellow => 'background-color:#ff0; ',
	on_bright_cyan => 'background-color:#0ff; ',
	on_bright_red => 'background-color:#f00; ',
	on_bright_blue => 'background-color:#00f; ',
	on_bright_magenta => 'background-color:#f0f; ',
	},
},